name: "Release"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser:
          - firefox
          - chromium
        build:
          - release
          - dev
        include:
          - browser: firefox
            extension: xpi
          - browser: chromium
            extension: crx

    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Get Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set Version In Update Manifest
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__VERSION__"
          replace: "${{ env.RELEASE_VERSION }}"
          regex: false
          include: "targets/${{ matrix.browser }}/${{ matrix.build }}/*.json"

      - name: Set Version In UI
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__VERSION__"
          replace: "${{ env.RELEASE_VERSION }}"
          regex: false
          include: "src/components/Settings.svelte"

      - name: Install all dependencies
        run: yarn install

      - name: Build
        run: yarn run build

      - name: Copy Manifest
        run: |
          cp ./targets/${{ matrix.browser }}/${{ matrix.build }}/manifest.json ./public

      - name: Pack Extension
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: tabby-${{ matrix.browser }}-${{ matrix.build }}.${{ matrix.extension }}
          directory: public

      - uses: montudor/action-zip@v1
        name: "Pack Extension"
        id: web-ext-build
        with:
          args: zip -qq -r tabby-${{ matrix.browser }}-${{ matrix.build }}.${{ matrix.extension }} public/build public/images public/index.html public/manifest.json

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            public/tabby-${{ matrix.browser }}-${{ matrix.build }}.${{ matrix.extension }}
            targets/${{ matrix.browser }}/${{ matrix.build }}/update-${{ matrix.browser }}-${{ matrix.build }}.json
