name: "Release"
on:
  push:
    tags:
      - "*.*.*"

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: actions/checkout@v1

      - name: Get Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: Set Version In Update Manifest
        uses: jacobtomlinson/gha-find-replace@v2
        with:
          find: "__VERSION__"
          replace: "${{ env.RELEASE_VERSION }}"
          regex: false
          include: "*.json"

      - name: Install all dependencies
        run: npm install

      - name: Build
        run: npm run build

      - name: Copy Extra files
        run: |
          cp ./manifest.json ./public
          cp ./update.json ./public

      - name: "Extension Build"
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: public
          filename: "tabby.xpi"

      - name: "Create Release"
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: |
            ${{ steps.web-ext-build.outputs.target }}
            update.json
